name: algorithm ci

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build:
    # Name the Job
    name: algorithm build
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [8.x, 10.x, 12.x]
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    # Runs the Super-Linter action
    - run: npm install
    - run: npm run test:ci

    # Send Message
    - name: Send Message
      uses: satak/webrequest-action@master
      with:
        url: https://api.twindy.org/message/wx
        method: POST
        payload: '{"content": "【Github Actions通知】\n\n[algorithm]发布成功", "contentType": 1}'
        headers: '{"Referer": "https://github.com"}'